theme: jekyll-theme-researcher
title: Preksha Nema
description: Ph.D. Student (CSE)  IIT Madras
avatar: https://raw.githubusercontent.com/PrekshaNema25/PrekshaNema25.github.io/master/images/preksha_image.jpg
